---

- name: Configure git editor
  git_config:
    name: core.editor
    scope: global
    value: nvim

- name: Configure git user
  git_config:
    name: user.name
    scope: global
    value: "Andr√© L. C. Moreira"

- name: Configure git email
  git_config:
    name: user.email
    scope: global
    value: alcm99@gmail.com

# TODO: clone via ssh
...
